version: '3.5'
services:

  loterioma_rng_db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  loterioma_rng_dbadmin:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  loterioma_rng:
    build: .docker/php
    container_name: loterioma_rng
    stdin_open: true
    tty: true
    ports:
      - 5501:80
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    volumes:
      - .:/var/www/html
    networks:
      - my-proxy-net

networks:
  my-proxy-net:
    external: true
    name: loterioma-net