version: '3'
services:
    php:
        build: .docker/php
        container_name: loterioma_rng
        ports:
          - 9901:80
        environment:
          - APACHE_DOCUMENT_ROOT=/var/www/html/public
        volumes:
          - .:/var/www/html